language: scala
sudo: false
before_install: umask 0022
scala:
  - 2.12.8
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
#  - sbt clean coverage test coverageReport
#  - bash <(curl -s https://codecov.io/bash)
